name: Insight Advantage
favicon: null
layout_spectrum: 0.14019252476282418
typography_spectrum: 0.5924999094568193
title: Insight Advantage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0093c7'
    - '#d3e8f3'
    - '#0000ff'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.7915576589293778
  lightness: 0.8037727968767285
  saturation: 0.22642847546376288
  rhythmicContrast: 0.75
purpose: []
